



export const registreUser = async (data) => {
  try {

  } catch (error) {
    throw new Error(error.message);
  }
};

export const loginUser = async (data) => {
  try {
  } catch (error) {
    throw new Error(error.message);
  }
};

export const getMe = async (data) => {
  try {
  } catch (error) {
    throw new Error(error.message);
  }
};
